import pandas as pd

col1 = []
col1.append('Alexis Chau')
col1.append('Owen Koh Lee')
col1.append('Julia Mason')
col1.append('Jeremiah-David Addai')
col1.append('Melissa Shun')
col1.append('Sarah Ali')
col1.append('Ethan Chen')
col1.append('Braxton Hoang')
col1.append('Kyle Lee')
col1.append('Bill Cheng')
col1.append('Winston Li')
col1.append('Michael Tovmasyan')
col1.append('Jolene Huey')
col1.append('Timothy Sujo')
col1.append('Axel Galicia Lona')
col1.append('Anthony Ge')
col1.append('Eric Yang')
col1.append('Julia Wong')
col1.append('Andrew Sung')
col1.append('Jeffrey Chou')
print(len(col1))
